### ISSUE TITLE
Instances still registered in Eureka server after shutdown

### ISSUE THREAD

**Issue by chefhoobajoob** [hazelcast/hazelcast-eureka#12]
I believe my application instances are going through an orderly shutdown (I still have to confirm this), but I am noticing that long after they have been shutdown, the Eureka server is still advertising the instances as 'UP'.

I'm assuming that this strategy is taking responsibility for unregistering at shutdown - is there anything I can do to verify whether or not `hazelcast-eureka` is in fact removing itself from the eureka server?

**Comment by chefhoobajoob** [comment]
I monitored the eureka server logs during application shutdown, and I don't see any sign of a DELETE request for the application. That's what I should be seeing if `hazelcast-eureka` is performing an orderly shutdown, isn't it?

**Comment by chefhoobajoob** [comment]
Nothing to address for the moment. I'll reopen or create a new issue if I can confirm specific unexpected behavior.

**Comment by googlielmo** [comment]
All right, thank you @chefhoobajoob !
