### ISSUE TITLE
Wrong ip used by docker node

### ISSUE THREAD

**Issue by moreiramarti** [hazelcast/hazelcast-eureka#14]
Hello,

I just implemented your plugin and it works but when my client registers with eureka, docker container hostname is used.
Is there a way to customize the ip adress or the hostname of a client?

Regards,
Martinho MOREIRA

**Comment by cforce** [comment]
Martinho <notifications@github.com> schrieb am Mo., 5. März 2018, 16:26:

**Comment by mesutcelik** [comment]
Hi @moreiramarti ,

Can you please give more info?
Are you launching hazelcast members as docker containers? Did you create your own docker image with hazelcast-eureka plugin? 
When you say client, do you hazelcast member?

**Comment by moreiramarti** [comment]
Hi,

Thanks you for taking time to answer me.
Yes, client is an hazelcast member.

I'm launching a custom app inside an Home made container (with my own image).

When i start my app it registers well with my eureka instance but the IP address registered on eureka seemed to be the docker node address and not the container one so my other apps instances can't communicate throught this address.

I need a way tout customize IP address of my app like it's possible with native eureka client (eureka.instance.ip-address).

Sorry if i'm not clear,
Martinho

**Comment by googlielmo** [comment]
Hi @moreiramarti 
You could try setting the `hazelcast.local.publicAddress` system property.
See http://docs.hazelcast.org/docs/3.9.3/manual/html-single/index.html#system-properties
Also see https://github.com/hazelcast/hazelcast-docker/blob/master/README.md#hazelcast-hello-world
Hope this helps.

**Comment by moreiramarti** [comment]
Thanks @googlielmo 
It's what I was looking for.

Thank you for your help.
