### ISSUE TITLE
Eureka 1.8.x Support

### ISSUE THREAD

**Issue by mesutcelik** [hazelcast/hazelcast-eureka#16]
Updating Eureka Client to version 1.8.7 didn't work with Spring Boot Eureka Server 
https://github.com/hazelcast/hazelcast-eureka/blob/v1.0.1/pom.xml#L19

**Comment by googlielmo** [comment]
Which version of Spring Boot Eureka Server?
They do use 1.8.7 on their latest master (v. 2.0.0.BUILD-SNAPSHOT): https://github.com/spring-cloud/spring-cloud-netflix/blob/ab87e735adeb3875a03dc143e92a3fe2c958fd63/spring-cloud-netflix-dependencies/pom.xml#L18
They have very old versions on previous tags though.

**Comment by mesutcelik** [comment]
I see it is working with 1.8.6. please check the description of https://github.com/hazelcast/hazelcast-eureka/pull/15
