### ISSUE TITLE
Receive Exception ConfigurationManager is already initialized with configuration org.apache.commons.configuration.MapConfiguration

### ISSUE THREAD

**Issue by mgoldver** [hazelcast/hazelcast-eureka#34]
When trying to create two Hazelcast Clients to point to two different Eureka clusters with use-classpath-eureka-client-props=false option, getting exception:

ConfigurationManager is already initialized with configuration org.apache.commons.configuration.MapConfiguration@65a4b9d6.

It seems that EurekaOne is trying to register another configuration under the same config manager, which has a check if it already exists.
I was successful at creating two connections when using eureka.client.props file with two different namespace(s).
I also was able to establish both connections with one configuration using classpath-eureka-client-props=false and the other pointing to the eureka.client.props file.

**Comment by leszko** [comment]
@mgoldver , yes if your application also registers in Eureka, you need to create two separate properties files. Please read the following blog post for more information: https://hazelcast.com/blog/hazelcast-auto-discovery-with-eureka/.

**Comment by bzaicsek-cxn** [comment]
I might misunderstand this, but it seems to me I have a similar problem. When I try to create a new Hazelcast instance with the same eureka settings, I can not because of the aforementioned error. Reproduction:

        Config c = new Config();
        c.setProperty("hazelcast.discovery.enabled", "true");
        c.setInstanceName("iname");
        c.getNetworkConfig().getJoin().getAwsConfig().setEnabled(false);
        c.getNetworkConfig().getJoin().getAzureConfig().setEnabled(false);
        c.getNetworkConfig().getJoin().getGcpConfig().setEnabled(false);
        c.getNetworkConfig().getJoin().getKubernetesConfig().setEnabled(false);
        c.getNetworkConfig().getJoin().getMulticastConfig().setEnabled(false);
        c.getNetworkConfig().getJoin().getTcpIpConfig().setEnabled(false);
        EurekaConfig ec = new EurekaConfig();
        ec.setEnabled(true);
        ec.setProperty("self-registration", "true");
        ec.setProperty("namespace", "hazelcast");
        ec.setProperty("use-metadata-for-host-and-port", "false");
        ec.setProperty("use-classpath-eureka-client-props", "false");
        ec.setProperty("shouldUseDns", "false");
        ec.setProperty("name", "hazelcast");
        ec.setProperty("serviceUrl.default", "http://localhost:8761/eureka");
        c.getNetworkConfig().getJoin().setEurekaConfig(ec);
        HazelcastInstance hzi = Hazelcast.getOrCreateHazelcastInstance(c);
        hzi.shutdown();
        
        //Code dies here:
        HazelcastInstance hzi2 = Hazelcast.getOrCreateHazelcastInstance(c);

Can you advise anything?

**Comment by chihaiaalex** [comment]
Same here!

**Comment by mgoldver** [comment]
> @mgoldver , yes if your application also registers in Eureka, you need to create two separate properties files. Please read the following blog post for more information: https://hazelcast.com/blog/hazelcast-auto-discovery-with-eureka/.

@leszko I guess my question was if it were possible to configure eureka-one discovery without the use of properties files. You answered my question.
Thank you.
