### ISSUE TITLE
Separated client and metadata scenario fails when automatic port negotiation is selected

### ISSUE THREAD

**Issue by tirun** [hazelcast/hazelcast-eureka#46]
Hello together, there seems to be a problem using hazelcast with eureka in a separted or metadata scenario (when application exposes rest endpoints too) in a spring boot application. 

if i choose a "server.port" manually at startup for both, application and hazelcast-client will be registered successfully. but when i let the environment choose the port by setting server.port=0 / @Value("${hazelcast.port:0}"). The port-update is not propagated to eureka (even if the log looks like: ... EurekaAutoServiceRegistration : Updating port to ....) that can be simply reproduced by setting the server.port to zero in the official examples here: https://github.com/hazelcast/hazelcast-code-samples/tree/master/hazelcast-integration/eureka/springboot-embedded.

**Comment by mesutcelik** [comment]
I tried this with `server.port=0` and it works fine.
https://github.com/hazelcast/hazelcast-code-samples/tree/master/hazelcast-integration/eureka/springboot-embedded#22-hazelcast-with-separate-eureka-client

`Tomcat started on port(s): 54512 (http) with context path ''`
```
Members {size:2, ver:6} [
	Member [192.168.46.215]:5703 - c34ed4af-63bd-4ef6-a3bd-a2f599a78383
	Member [192.168.46.215]:5701 - 39fd28b1-7271-4dd9-8826-d80dd48a7738 this
]
```

Are you starting your apps one by one or at the same time? You might be hitting to start in split brain mode if you launch both simultaneously. In this case, you need to wait 5 more minutes for the next join request.

**Comment by tirun** [comment]
Thanks for your quick reply! 

What i've done from the fresh-cloned example: 
- altered `com.hazelcast.samples.eureka.Application:14` to `@Value("${hazelcast.port:0}")`
- added line to `src\main\resources\bootstrap.properties`: `server.port=0`

Staerted the eureka-server (from exapmles) and spawned the Application 5 times (with a delay of a couple of seconds). After one houre all services are up and running but Eureka shows only one Application (The five hazelast clients seems to be fine). 

![grafik](https://user-images.githubusercontent.com/12750228/75605153-80e6b980-5ae0-11ea-8053-26e9b0d70c49.png)

**Comment by mesutcelik** [comment]
Hi @tirun ,
This looks like more of a Spring Boot issue.
I followed this, set `server.port=0` and started two `ServiceRegistrationAndDiscoveryClientApplication` and I see similar screen that you see.

I think `server.port=0` random port usage is not supported by Eureka.

**Comment by tirun** [comment]
Hello @mesutcelik,

indeed, you're right. If i comment out the hazelcast stuff from the example i get the same issue.

Thanks for your help!
