### ISSUE TITLE
Custom Eureka metadata?

### ISSUE THREAD

**Issue by SledgeHammer01** [hazelcast/hazelcast-eureka#55]
How do you override the Eureka client metadata? Seems to ignore the standard props:

```
eureka.instance.home-page-url=https://${eureka.instance.hostname}:${server.port}/
eureka.instance.status-page-url=https://${eureka.instance.hostname}:${server.port}/info
eureka.instance.health-check-url=https://${eureka.instance.hostname}:${server.port}/health

```

**Comment by hasancelik** [comment]
Hi @SledgeHammer01,

You can configure Eureka client properties via `eureka-client.properties` file:
https://github.com/hazelcast/hazelcast-eureka#properties-file

You can find related code samples, [here](https://github.com/hazelcast/hazelcast-code-samples/tree/master/hazelcast-integration/eureka/springboot-embedded).
