### ISSUE TITLE
Allow to pass EurekaClient instance to EurekastOneDiscoveryStrategyFactory using code

### ISSUE THREAD

**Issue by tjuchniewicz** [hazelcast/hazelcast-eureka#6]
We should allow to pass `EurekaClient` instance created in microservice to `EurekastOneDiscoveryStrategyFactory` using code. By default hazelcast-eureka creates `EurekaClient` using `eureka-client.properties` file. This will allow to share existing Eureka configuration.

**Comment by igorbljahhin** [comment]
+1
